### PR TITLE
Fix the rebroadcast server

### LINKED ISSUE #28: When one client disconnects, the server sometimes disconnects other clients too?
Good first bug for someone who wants to learn about async in Rust!

I have basically no idea how the current server works, it's mostly just adapted from https://github.com/snapview/tokio-tungstenite/blob/master/examples/server.rs

### PR DESCRIPTION
**Pull request by rictic**
Fixes #28

This took a long time for such a simple fix, but I learned a lot about async and futures, and a little bit about tokio!

What I should have been learning about was WebSockets. You see, there are a few different types of messages you can send with WebSockets. You can send text, you can send binary, and there's this special ping/pong format for some reason? But also one of the kinds of messages is a close message.

So, our rebroadcast server, what it does is it rebroadcasts every message received to every other client.

Including close messages.

So, that explains why when one client closes, usually all of them do. Because we rebroadcast the close message from the server to all the other clients, asking them to close the connection!

Argh!

### CODE REVIEW

File: server/src/main.rs [hunk 1]
```diff
@@ -79,3 +87,65 @@ async fn main() -> Result<(), IoError> {
 
     Ok(())
 }
+
+#[cfg(test)]
+mod tests {
```
Comment (cdata) [inline server/src/main.rs:92]: 💯

Comment (cdata) [reply server/src/main.rs:92]: Do these get omitted in release builds somehow thanks to the `cfg` trait?

**Review by cdata — APPROVED** [review]

File: server/src/main.rs (hunk 1 above)
Comment (rictic) [reply server/src/main.rs:92]: Yep! They're only built when you run `cargo test`
